---
title: "cDNA"
author: "Sarah Tanja"
date: "5/31/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Protocol
For each RNA sample, it is recommended to produce cDNA in duplicate or triplicate to guard against potential contamination or pipetting errors.  


### Step 1
- [ ] Label 0.5ml vials with RNA sample ID (ex. 001) and a duplicate indicator (ex. a, b, c)

Aim for $100ng of RNA$ in $18\mu l$ of  $H_{2}O$

$$ RNA \mu l = \frac{100 ng }{qubit score (\frac{ng}{\mu l}) } $$
    
    
$$ sigma H_{2}O (\mu l) = \frac{100 (ng) }{qubit score (\frac{ng}{\mu l}) - 18 \mu l $$
  
*ex. If qubit scores average 100ng of RNA, add 1$/mu$l of RNA to 17$/mu$l of sigma H$_[{2}$0*
*ex. If qubit scores average 50ng of RNA, add 2$/mu$l of RNA to 16$/mu$l of sigma H$_[{2}$0*

- [ ] Add 2 $/mu$l of RNA sample to each corresponding 0.5ml vial
- [ ] Add 16 $/mu$l of sigma water


- [ ] Add 1 $/mu$l of oligo dT primer
- [ ] Incubate at 70$^{\circ}$C for 5 minutes in a thermal cycler 

### Step 2
- [ ] Make a master mix of the following components, 
      multiplied by the number of sample vials you are working with.
       
      
      5$/mu$l MMLV Buffer
      1.25$/mu$l dNTP
      0.5$/mu$l MMLV
      
- [ ] Add 6.75$/mu$l of master mix to each sample vial
- [ ] Incubate at 42$^{\circ}$C for 1 hour in a thermal cycler 
- [ ] Incubate at 95$^{\circ}$C for 3 minutes in a thermal cycler
- [ ] Store frozen in a standard -20$^{\circ}$C freezer

# Method Narrative

We took 11 extracted gill-tissue RNA samples from each of treatments A (chronic 18C) and B (variable cycling) and 10 extracted RNA samples from the control group C ()

# Detailed Narrative
05/31/22
Aidian Coyle and Sarah Tanja
Completed 18 samples in duplicate,and labelled the duplicates a & b
Not all samples had qubit score... we used the qubit scores generated by Chris Mantegna as a subsample, they ranged from __ to ___ and averaged 52ng of RNA. To get 100ng of RNA, we added 2$/mu$l of RNA extract to 16$/mu$l of sigma water. 
**Added 2$/mu$l of oligo dT primer instead of 1$/mu$l!**

Peltier Thermal Cycler (PTC-200)

Master Mix made for 18 samples, 36 total working vials

06/01/22
Sarah Tanja
14 samples
28 total working vials

**Incubated for 10min instead of 5 at 70$^{\circ}$C :(**

Master Mix:
5$/mu$l buffer * 30 = 150$/mu$l
1.25$/mu$l dNTP * 28 = 37.5$/mu$l
0.5$/mu$l MMLV *28 = 15$/mu$l